# Generated by Django 4.2.6 on 2023-10-23 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='authour',
            new_name='author',
        ),
    ]
